# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058e3ee161787eecc0a82295ad5ad3e6641e614f95884e6c6398f608b585fb5bbf97d08d4f9b9939e2a55631e7765a90246caa6a1bd983a68cdc64bf8ff77cec

test:
  secret_key_base: 3ec1cf6814fbe6a61b2369b54f1857de435f9f2e53fe38b91ea40edfb29e4397c2cf66aeee8cdfa6eec0db0fcadb245b1f72bfb5397378d89c05e10903e2e4c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
